### ISSUE TITLE
Driver do obsługi LoRa pod linuxem (Userspace)

### ISSUE THREAD

**Issue by bykowskiolaf** [BuzzVerse/lora_linux_driver#1]
- Beaglebone Black -  przygotowanie image na karcie SD
- Podłączenie LoRa po magistrali SPI
- Napisanie drivera w user space - IOCTL. (SPI - magistrala komunikacji szeregowej: https://en.wikipedia.org/wiki/Serial_Peripheral_Interface)
- https://www.youtube.com/watch?v=0nVNwozXsIc

API:
- Odczytanie statusu
- Transmisja RF
- Odbiór RF
- Wpisanie odebranych danych do pliku (format binarny).

**Comment by janr4** [comment]
Struktura ramki:

[ramka_lora.txt](https://github.com/BuzzVerse/lora_linux_driver/files/13706458/ramka_lora.txt)

**Comment by LittleAzriel** [comment]
Zrobione:

- Odczytywanie ramki bez sprawdzania sumy kontrolnej
- Na BealgeBonie jest postawiony działający Linux
- System jest przygotowany, aby na dev/spi rozpoznać LoRe
- Określono format ramki
- Podstawowe rozpoznawanie wielkości ramki jest zaimplementowane i przetestowane na plikach testowych
- Draft funkji sumy kontrolnej

Do zrobienia:

- Podłączenie LoRy i sprawdzenie poprawności działania w dev/spi
- Podłączenie drugiej LoRy i sprawdzenie jej w dev/spi
- Weryfikacja radiowej transmisji dwukierunkowej

**Comment by pkamoda-shani** [comment]
Dodajcie do tego ticketa proszę program który napisaliście do parsowania ramki. Zróbcie branch i tam go dodajcie. Jeżeli nie wiecie jak napiszcie na kanale #github
